### ISSUE TITLE
Activating throws fatal error (php 7.3.5), latest ACF pro

### ISSUE THREAD

**Issue by ts-mz** [Log1x/acf-editor-palette#21]
Hi, I just tried your color palette ACF plugin, but it throws a fatal error in a fresh WP install, latest ACF, php 7.3.5

"Fatal error: Uncaught Error: Class 'Log1x\AcfEditorPalette\Field' not found"

**Comment by Log1x** [comment]
Are you using the release zip? https://github.com/Log1x/acf-editor-palette/releases/download/v1.0.6/acf-editor-palette-v1.0.6.zip

**Comment by ts-mz** [comment]
Apparently, I wasn't. Thanks a lot for your reply!
