### ISSUE TITLE
Empty palette in editor

### ISSUE THREAD

**Issue by sefrijn** [Log1x/acf-editor-palette#23]
First of all - Love your ACF Composer!
I tried ACF Editor Palette just now with Sage 10 (dev-master), added an editor_palette field. The field looks empty in the WP editor:

![Screenshot 2021-04-13 at 20 56 11](https://user-images.githubusercontent.com/1764694/114605763-b4f84c00-9c9a-11eb-9935-e715fc785023.png)
(so... there is nothing beneath this)

Steps to reproduce this problem:

1. Install Sage 10 `composer create-project roots/sage theme-name dev-master`
2. `yarn` + `yarn start`
3. Add a color palette to Sage 10 `app/setup.php` (which is working with default WP blocks)
4. Install ACF Pro and activate
5. Install ACF Composer with `composer require log1x/acf-composer`  + `wp acorn vendor:publish` (which throws an error but seems to succeed: 
```
In VendorPublishCommand.php line 277:
Call to undefined function Illuminate\Foundation\Console\base_path() 

```
6. Install ACF Editor Palette with `composer require log1x/acf-editor-palette`
7. Generate Example `wp acorn acf:field Example`
8. Use this code
```
$example
->addRepeater('items')
   ->addText('item')
->endRepeater()
->addField('new_color', 'editor_palette')
   ->setConfig('return_format', 'slug');
```

Curious to hear if I'm doing something wrong, or if this is a bug. 
PHP version 7.4.15
Thanks!

**Comment by sefrijn** [comment]
Just found out that if I manually download the ACF Editor Palette .zip and install the plugin, the color palette actually works!

But I don't suppose that is the idea and it should work with Sage 10 by just running `composer require log1x/acf-editor-palette`?

**Comment by Log1x** [comment]
You need to run `composer require log1x/acf-editor-palette` from Bedrock, not Sage.
