### ISSUE TITLE
The clear button doesn't trigger a block update

### ISSUE THREAD

**Issue by corentin-gautier** [Log1x/acf-editor-palette#24]
Hi !

Awesome plugin ! 

I just have on issue with it : the clear button doesn't trigger an update, which means that the last selected color stays on until I save the post and reload the page.

Other than that it's brilliant, would be awesome to have it on wpackagist too !

Thanks !

EDIT : Saving and reloading doesn't register that the clear button has been clicked. The only way I've found to register the change is to edit another acf field, and it sometimes doesn't work either

**Comment by iamswain** [comment]
I've noticed that when pressing the "clear" button, and editing another ACF field, it clears the other Editor Palette fields too.

**Comment by corentin-gautier** [comment]
@iamswain yup, fixed that too in my PR

**Comment by Log1x** [comment]
release pushed :)
