### ISSUE TITLE
Default color doesn't use the selected Return Format

### ISSUE THREAD

**Issue by lynxwd** [Log1x/acf-editor-palette#26]
Hi

Great plugin, thanks!

I have found an issue when using Default color with color, text class or background class Return Format.

Default color pre-selects the color in the color palette, but uses the color slug regardless of the selected Return Format. So where a default color is being used for text / background classes, it doesn't display this color in the Block editor preview.

On saving, the correct format is used in the front-end, but still not in the editor.

Only refreshing the page after saving, selecting another option then reselecting the default color or making a selection in another color palette in the same block returns the color in the selected format in the editor.

**Comment by Log1x** [comment]
Extremely sorry for the delay on getting this fixed. I replicated the issue and was able to get it fixed in v1.1.1.
