### ISSUE TITLE
Allow field to work in options pages

### ISSUE THREAD

**Issue by davidwebca** [Log1x/acf-editor-palette#28]
Hi!

The field doesn't work properly in options pages, mainly because the wp-component file doesn't get enqueued. I've narrowed it down to line 275 : https://github.com/Log1x/acf-editor-palette/blob/master/src/Field.php#L275

What is this supposed to do? From what I understand, it enqueues the styles only if the wp-component script is not enqueued? Why is that?

Should it not be the reverse and could it not be simply added as an array of dependencies to wp_enqueue_style / wp_enqueue_scripts a few lines under?

**Comment by Log1x** [comment]
don't 100% recall my reasoning behind that but feel free to do a PR if what you mentioned works as intended
