### ISSUE TITLE
Support for theme.json ?

### ISSUE THREAD

**Issue by em-piguet** [Log1x/acf-editor-palette#30]
Hi nice plugin! 
Are you planning to support theme.json ? https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-json/

**Comment by enoversum** [comment]
A solid +1 from me for this :) !

**Comment by Log1x** [comment]
did they really not give us any functions to access theme.json? lol

**Comment by Log1x** [comment]
```php
$theme = class_exists('WP_Theme_JSON') ?
    \WP_Theme_JSON_Resolver::get_merged_data()->get_settings() : [];

if (! empty($theme = $theme['color']['palette']['theme'])) {
    $palette = array_merge($palette, $theme);
}
```

fun

**Comment by freeaanzee** [comment]
Noticed this problem today, while playing around with theme.json. Couldn't easily find how to access the JSON settings, I'm glad you did. Works like a charm, thanks for the fix!

**Comment by daverobertson** [comment]
> did they really not give us any functions to access theme.json? lol

better late than never! (5.9)
https://make.wordpress.org/core/2022/01/04/new-api-to-access-global-settings-styles/

haven't tried it with this plugin yet but hope it is useful...

**Comment by Log1x** [comment]
> @Log1x , do you want me to create a PR?

A PR would be great! Thank you

**Comment by Log1x** [comment]
Added in v1.1.0.

Very sorry for the delay.
