### ISSUE TITLE
Apparent issue with ACF Pro 5.10

### ISSUE THREAD

**Issue by benupham** [Log1x/acf-editor-palette#31]
Hi, 

It would appear that the field group editing experience with the editor palette field is (sort of) broken with ACF Pro 5.10. Instead of displaying the color name and a swatch, it looks like the wrapper HTML is being displayed as well. See this screenshot. 
<img width="1441" alt="Screen Shot 2021-08-27 at 9 28 21 AM" src="https://user-images.githubusercontent.com/5560040/131159683-76e2c7a5-9cc0-42df-a103-c093f75b5bb9.png">

...confirmed it is 5.10 related as the labels render fine when I rolled back. Could this be related to the new [HTML escaping defaults](https://www.advancedcustomfields.com/resources/html-escaping/)? 

Thanks,
Ben

**Comment by Log1x** [comment]
This should be fixed by the ACF team in 5.10.2

**Comment by Log1x** [comment]
Confirmed this has been fixed in 5.10.2!

**Comment by OTBD** [comment]
hey Brandon - @Log1x , not sure if you're keeping this repo updated but just found it (and superb work!) I've just found the same issue is back that Ben has. I'm using ACF Pro v6.2.7 and running into this issue. Is there a workaround I can do to fix this? 

Thanks!

**Comment by Log1x** [comment]
> I'm using ACF Pro v6.2.7 and running into this issue.

hey, fun! i'll look into this when I get time.
