### ISSUE TITLE
Deprecation error with latest Admin Columns: ACF add-on (3.0.2)

### ISSUE THREAD

**Issue by daverobertson** [Log1x/acf-editor-palette#36]
Hi,

I'm using this plugin in conjunction with Admin Columns Pro and its ACF add on. Upon upgrading the ACF add-on to the latest v 3.0.2, the following error appears on visiting the list view of a CPT in the WP Admin:

```
ErrorException (E_USER_DEPRECATED)
ACA\ACF\Column::get_acf_field_option is <strong>deprecated</strong> since version NEWVERSION with no alternative available.
```

...which Whoops can't seem to get past. From the stack trace:

```
15
ACA\ACF\Column get_acf_field_option
/[...]/wp-content/plugins/acf-editor-palette/plugin.php101
14
class@anonymous/[...]/wp-content/plugins/acf-editor-palette/plugin.php:14$0 Log1x\AcfEditorPalette\{closure}
/[...]/wp-includes/class-wp-hook.php307
...
```

I'm not familiar with the ACP API, but changing line 101 from
`$column->get_acf_field_option('type') !== $this->name ||`
to
`$column->get_type() !== $this->name ||`
seemed to get things working again, per [this doc](https://docs.admincolumns.com/article/53-class-ac-column). Not sure about any side-effects, etc...

HTH / Thanks!

**Comment by Log1x** [comment]
Want to do a PR?

**Comment by Log1x** [comment]
I think `$column->get_type()` should be `$column->get_field_type()` – needs a quick test though.
