### ISSUE TITLE
PHP Error in Field.php

### ISSUE THREAD

**Issue by tjgavlick** [Log1x/acf-editor-palette#43]
Hello! Thank for you for this plugin, first off.

The issue I'm having is that it's crashing on my installation's admin interface — I'm unable to load a block's side panel that uses this field, for example, nor am I able to edit a field group that uses this field type. This might be an interaction with ACF 6.0.0, as I have other installations running ACF 5.12.x that are doing just fine.

Using the latest release (1.1.3) of this plugin. My error log is showing a multitude of these:

PHP Fatal error:  Uncaught TypeError: current(): Argument #1 ($array) must be of type array, bool given in [client info removed]\wp-content\plugins\acf-editor-palette\src\Field.php:49
Stack trace:
#0 [client info removed]\wp-content\plugins\acf-editor-palette\src\Field.php(49): current()
#1 [client info removed]\wp-content\plugins\acf-editor-palette\src\Field.php(170): Log1x\AcfEditorPalette\Field->palette()
#2 [client info removed]\wp-includes\class-wp-hook.php(308): Log1x\AcfEditorPalette\Field->render_field_settings()
#3 [client info removed]\wp-includes\class-wp-hook.php(332): WP_Hook->apply_filters()
#4 [client info removed]\wp-includes\plugin.php(517): WP_Hook->do_action()
#5 [client info removed]\wp-content\plugins\advanced-custom-fields-pro\includes\admin\views\field-group-field.php(150): do_action()
#6 [client info removed]\wp-content\plugins\advanced-custom-fields-pro\includes\api\api-helpers.php(443): include('...')
#7 [client info removed]\wp-content\plugins\advanced-custom-fields-pro\includes\admin\views\field-group-fields.php(79): acf_get_view()
#8 [client info removed]\wp-content\plugins\advanced-custom-fields-pro\includes\api\api-helpers.php(443): include('...')
#9 [client info removed]\wp-content\plugins\advanced-custom-fields-pro\includes\admin\admin-field-group.php(483): acf_get_view()
#10 [client info removed]\wp-admin\includes\template.php(1409): acf_admin_field_group->mb_fields()
#11 [client info removed]\wp-admin\edit-form-advanced.php(688): do_meta_boxes()
#12 [client info removed]\wp-admin\post.php(206): require('...')
#13 {main}
  thrown in [client info removed]\wp-content\plugins\acf-editor-palette\src\Field.php on line 49

**Comment by Log1x** [comment]
Are you using `theme.json` or `add_theme_support`?

I'll push a fix for this but you might be able to temporarily solve it with `add_theme_support('editor-color-palette', []);` (assuming you're using `theme.json`)

**Comment by Log1x** [comment]
This should be fixed in v1.1.4. Let me know if you have any issues.

**Comment by tjgavlick** [comment]
Hey, thanks for the speed on this! I tried 1.1.4, and it fixed that one while generating a similar error in a different file (below). However, `add_theme_support('editor-color-palette', []);` did the trick — perhaps it would be easier to add this line to the installation instructions than it would be to keep chasing down these (possibly rare) cases?

New error is as follows:

PHP Fatal error:  Uncaught TypeError: current(): Argument #1 ($array) must be of type array, bool given in [client info removed]\wp-content\plugins\acf-editor-palette\src\Concerns\Palette.php:19
Stack trace:
#0 [client info removed]\wp-content\plugins\acf-editor-palette\src\Concerns\Palette.php(19): current()
#1 [client info removed]\wp-content\plugins\acf-editor-palette\src\Field.php(132): Log1x\AcfEditorPalette\Field->palette()
#2 [client info removed]\wp-includes\class-wp-hook.php(308): Log1x\AcfEditorPalette\Field->render_field_settings()
#3 [client info removed]\wp-includes\class-wp-hook.php(332): WP_Hook->apply_filters()
#4 [client info removed]\wp-includes\plugin.php(517): WP_Hook->do_action()
#5 [client info removed]\wp-content\plugins\advanced-custom-fields-pro\includes\admin\views\field-group-field.php(150): do_action()
#6 [client info removed]\wp-content\plugins\advanced-custom-fields-pro\includes\api\api-helpers.php(443): include('...')
#7 [client info removed]\wp-content\plugins\advanced-custom-fields-pro\includes\admin\views\field-group-fields.php(79): acf_get_view()
#8 [client info removed]\wp-content\plugins\advanced-custom-fields-pro\includes\api\api-helpers.php(443): include('...')
#9 [client info removed]\wp-content\plugins\advanced-custom-fields-pro\includes\admin\admin-field-group.php(483): acf_get_view()
#10 [client info removed]\wp-admin\includes\template.php(1409): acf_admin_field_group->mb_fields()
#11 [client info removed]\wp-admin\edit-form-advanced.php(688): do_meta_boxes()
#12 [client info removed]\wp-admin\post.php(206): require('...')
#13 {main}
  thrown in [client info removed]\wp-content\plugins\acf-editor-palette\src\Concerns\Palette.php on line 19

**Comment by Log1x** [comment]
Could you try changing `??` to `?:` at https://github.com/Log1x/acf-editor-palette/blob/master/src/Concerns/Palette.php#L19 and see if it fixes it? If so you can do a PR or just let me know and I'll push a fix.

**Comment by Log1x** [comment]
Dived into this myself. Should be fixed in https://github.com/Log1x/acf-editor-palette/pull/45
