### ISSUE TITLE
Selection being forgotten

### ISSUE THREAD

**Issue by Jamiewarb** [Log1x/acf-editor-palette#5]
I am getting an issue where, when loading a page to edit that uses this field, the saved result is not being selected. Saving the page then erases the value, as it no longer has a value selected.

I believe it must be caused by the plugin not retrieving the value from the database correctly after its been stored.

## Expected Outcome

When refreshing an edit screen with an editor palette on it, the chosen colour remains

## Actual Outcome

When refreshing the page, no colour is selected anymore.

## Steps to Reproduce

1. Create a fresh WordPress install
2. Add ACF Pro, and acf-editor-palette, and activate both plugins
3. Create a new Field Group in ACF [see image 1].
 
```
Title: Test

Field label: palette
Field name: palette
Field type: Editor Palette
Return Format: Color
```

4. Publish the field.
5. Go to the Sample Post (or create a post if it's not there).
6. Observe the editor palette widget on the post edit screen.
7. Choose a colour, then click save (or publish).
8. Observe the post is saved.
9. Refresh the edit post screen.
10. Observe the colour is no longer selected. [2]

[1] 
![image](https://user-images.githubusercontent.com/2754728/104760433-4407cd80-5759-11eb-9af6-34d8e6e2fa73.png)

[2] 
![image](https://user-images.githubusercontent.com/2754728/104760670-9812b200-5759-11eb-9e79-9fc3840c1e30.png)

## Logs

I can see the following errors when I activate the Debug Bar plugin too:

```
file: "wp-content/plugins/acf-editor-palette-1.0.2/src/Field.php"
key: "f27a6d977a01bb7c9d4b91d6992bec8a"
line: 46
message: "Only variables should be passed by reference"
stack: (16) ["Log1x\A\Field->palette()", "Log1x\A\Field->render_field()", "do_action_ref_array('acf/render_field/type=editor_palette')", "_acf_apply_hook_variations()", "do_action('acf/render_field')", "acf_render_field()", "acf_render_field_wrap()", "acf_field_repeater->render_field()", "do_action_ref_array('acf/render_field/type=repeater')", "_acf_apply_hook_variations()", "do_action('acf/render_field')", "acf_render_field()", "acf_render_field_wrap()", "acf_render_fields()", "acf_ajax_fetch_block()", "do_action('wp_ajax_acf/ajax/fetch-block')"]
type: "notice"
```

```
file: "wp-includes/general-template.php"
key: "56cf8a85df762dcf16e266ed5153c259"
line: 4837
message: "Array to string conversion"
stack: (17) ["__checked_selected_helper()", "checked()", "Log1x\A\Field->render_field()", "do_action_ref_array('acf/render_field/type=editor_palette')", "_acf_apply_hook_variations()", "do_action('acf/render_field')", "acf_render_field()", "acf_render_field_wrap()", "acf_field_repeater->render_field()", "do_action_ref_array('acf/render_field/type=repeater')", "_acf_apply_hook_variations()", "do_action('acf/render_field')", "acf_render_field()", "acf_render_field_wrap()", "acf_render_fields()", "acf_ajax_fetch_block()", "do_action('wp_ajax_acf/ajax/fetch-block')"]
type: "notice"

```

**Comment by Log1x** [comment]
> However, if you select something and then clear it, the return value is still an array too, and not the default value, so that looks like a separate bug. I'll open a separate issue for that

Thanks for confirming. [I suspected this](https://github.com/Log1x/acf-editor-palette/pull/3#issuecomment-748606867) but I haven't had the time to implement this plugin as a daily driver on any of my sites so I haven't been able to personally battle test it yet.

**Comment by Jamiewarb** [comment]
No worries. 

If you have the time to fix this bug, that would be amazing. However, if you don't, then I can put in a PR for a temporary fix, like this:

```php
public function render_field($field) {
    ...
    $color_slug = is_array($field['value']) ? $field['value']['slug'] : $field['value'];
    ...
}
```

That will at least get the colour saving properly. I can then come back and do the proper fix once I've some spare time, unless you get to it before me :)

**Comment by Jamiewarb** [comment]
Thanks for merging! And thanks again for making the plugin, it's saved me a load of time already
