### ISSUE TITLE
Feature request: Support including the plugin with a theme

### ISSUE THREAD

**Issue by ElvarP** [Log1x/acf-editor-palette#52]
What I mean is that I want to bundle this plugin with a theme I'm creating. Including the plugin in functions.php works fine, except the css and js files don't load in the Full Site Editor. I've been tinkering trying to get it to work  but have not been able to come up with a solution.

**Comment by Log1x** [comment]
Any particular reason you want to bundle it with a theme vs using it as an [mu-plugin](https://wordpress.org/documentation/article/must-use-plugins/) alongside something like [Bedrock](https://github.com/roots/bedrock)?

In any case, I'm not sure the best approach for something like this given that we use `plugin_dir_url()` to handle the asset pathing. I've never tried to bundle a plugin inside of a theme before.
