### ISSUE TITLE
Clearing field doesn't change what value is returned from database

### ISSUE THREAD

**Issue by Jamiewarb** [Log1x/acf-editor-palette#6]
~Note: This may be related to #5, and may be fixed when that is.~

#5 is, in short, when selecting a colour, the `$field['value']` is coming back as an array of colours. The code expects it to be just be a slug.

While investigating this, I noticed that, when using the `Clear` button to remove the selected value, the `$field['value']` still comes back with the previously selected colours array of values. This happens even when the field has a default value.

That means there's no way to clear the value and get back to a default value.

Reproduction steps are identical to those in #5, except with the addition of selecting a default value.

**Comment by Log1x** [comment]
Working on this and a few other things now.
