### ISSUE TITLE
Fatal Error from use of Union Types for PHP versions < 8

### ISSUE THREAD

**Issue by ajskelton** [Log1x/acf-editor-palette#60]
I'm working on updating some sites that are still on PHP 7.4. I'm in the process of getting them updated to 8.2, but in the meantime I needed to update this plugin to deal with the errors from the ACF 6.3 update. 

When attempting to update this plugin I started getting the following error:

> PHP Fatal error: During class fetch: Uncaught ParseError: syntax error, unexpected '|', expecting ';' or '{' in /nas/content/live/sitename/wp-content/plugins/acf-editor-palette/src/Concerns/Asset.php:39

Looking into it the manifest function has a Union Type which is only allowed in PHP 8+. The Repo still lists the PHP requirement as >= 7.2, so either that should be bumped up to 8 or the Union Type should be removed.

**Comment by Log1x** [comment]
Hey, no problem. Feel free to submit a PR to patch that.

**Comment by Log1x** [comment]
Ah I see, I did it recently with https://github.com/Log1x/acf-editor-palette/commit/ac707a6aa7ed3211606cd0127bff1de83cb7925b – I didn't mean too.

Let me know if you need me to do the PR.

**Comment by Log1x** [comment]
perfect! release pushed. thank you and sorry about that.
